/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountSelector: typeof import('./components/settings/AccountSelector.vue')['default']
    AccountSettings: typeof import('./components/settings/AccountSettings.vue')['default']
    ChatInput: typeof import('./components/chat/ChatInput.vue')['default']
    DeepThinkingModal: typeof import('./components/chat/DeepThinkingModal.vue')['default']
    Dialog: typeof import('./components/common/Dialog.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    IconAdd: typeof import('./components/icons/IconAdd.vue')['default']
    IconArrowUp: typeof import('./components/icons/IconArrowUp.vue')['default']
    IconBrain: typeof import('./components/icons/IconBrain.vue')['default']
    IconChat: typeof import('./components/icons/IconChat.vue')['default']
    IconCheck: typeof import('./components/icons/IconCheck.vue')['default']
    IconChevronDown: typeof import('./components/icons/IconChevronDown.vue')['default']
    IconClose: typeof import('./components/icons/IconClose.vue')['default']
    IconCopy: typeof import('./components/icons/IconCopy.vue')['default']
    IconDelete: typeof import('./components/icons/IconDelete.vue')['default']
    IconDisable: typeof import('./components/icons/IconDisable.vue')['default']
    IconEdit: typeof import('./components/icons/IconEdit.vue')['default']
    IconError: typeof import('./components/icons/IconError.vue')['default']
    IconExport: typeof import('./components/icons/IconExport.vue')['default']
    IconInfo: typeof import('./components/icons/IconInfo.vue')['default']
    IconLink: typeof import('./components/icons/IconLink.vue')['default']
    IconModels: typeof import('./components/icons/IconModels.vue')['default']
    IconPlus: typeof import('./components/icons/IconPlus.vue')['default']
    IconSend: typeof import('./components/icons/IconSend.vue')['default']
    IconSettings: typeof import('./components/icons/IconSettings.vue')['default']
    IconSpinner: typeof import('./components/icons/IconSpinner.vue')['default']
    IconSuccess: typeof import('./components/icons/IconSuccess.vue')['default']
    IconUser: typeof import('./components/icons/IconUser.vue')['default']
    IconWarning: typeof import('./components/icons/IconWarning.vue')['default']
    LoadingOverlay: typeof import('./components/common/LoadingOverlay.vue')['default']
    MarkdownRenderer: typeof import('./components/common/MarkdownRenderer.vue')['default']
    MessageActionsFooter: typeof import('./components/chat/MessageActionsFooter.vue')['default']
    MessageItem: typeof import('./components/chat/MessageItem.vue')['default']
    MessageList: typeof import('./components/chat/MessageList.vue')['default']
    ModelCard: typeof import('./components/models/ModelCard.vue')['default']
    ModelForm: typeof import('./components/models/ModelForm.vue')['default']
    ModelsModal: typeof import('./components/models/ModelsModal.vue')['default']
    ProxySettingsModal: typeof import('./components/settings/ProxySettingsModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollToBottom: typeof import('./components/chat/ScrollToBottom.vue')['default']
    SettingsModal: typeof import('./components/settings/SettingsModal.vue')['default']
    SidebarNav: typeof import('./components/sidebar/SidebarNav.vue')['default']
    TestResultDialog: typeof import('./components/models/TestResultDialog.vue')['default']
    Toast: typeof import('./components/common/Toast.vue')['default']
    ToggleSwitch: typeof import('./components/common/ToggleSwitch.vue')['default']
  }
}
