/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChatContainer: typeof import('./components/chat/ChatContainer.vue')['default']
    ChatInput: typeof import('./components/chat/ChatInput.vue')['default']
    ChatMessage: typeof import('./components/ChatMessage.vue')['default']
    Dialog: typeof import('./components/common/Dialog.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    EmptyState: typeof import('./components/chat/EmptyState.vue')['default']
    IconAdd: typeof import('./components/icons/IconAdd.vue')['default']
    IconChat: typeof import('./components/icons/IconChat.vue')['default']
    IconCheck: typeof import('./components/icons/IconCheck.vue')['default']
    IconChevronDown: typeof import('./components/icons/IconChevronDown.vue')['default']
    IconClose: typeof import('./components/icons/IconClose.vue')['default']
    IconCopy: typeof import('./components/icons/IconCopy.vue')['default']
    IconDelete: typeof import('./components/icons/IconDelete.vue')['default']
    IconDisable: typeof import('./components/icons/IconDisable.vue')['default']
    IconEdit: typeof import('./components/icons/IconEdit.vue')['default']
    IconError: typeof import('./components/icons/IconError.vue')['default']
    IconInfo: typeof import('./components/icons/IconInfo.vue')['default']
    IconLink: typeof import('./components/icons/IconLink.vue')['default']
    IconModels: typeof import('./components/icons/IconModels.vue')['default']
    IconPlus: typeof import('./components/icons/IconPlus.vue')['default']
    IconSend: typeof import('./components/icons/IconSend.vue')['default']
    IconSpinner: typeof import('./components/icons/IconSpinner.vue')['default']
    IconSuccess: typeof import('./components/icons/IconSuccess.vue')['default']
    IconWarning: typeof import('./components/icons/IconWarning.vue')['default']
    LoadingOverlay: typeof import('./components/common/LoadingOverlay.vue')['default']
    MarkdownRenderer: typeof import('./components/common/MarkdownRenderer.vue')['default']
    MessageActionsFooter: typeof import('./components/chat/MessageActionsFooter.vue')['default']
    MessageItem: typeof import('./components/chat/MessageItem.vue')['default']
    MessageList: typeof import('./components/chat/MessageList.vue')['default']
    ModelsModal: typeof import('./components/models/ModelsModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarNav: typeof import('./components/sidebar/SidebarNav.vue')['default']
    SideMenu: typeof import('./components/sidebar/SideMenu.vue')['default']
    StatsPanel: typeof import('./components/sidebar/StatsPanel.vue')['default']
    TypingIndicator: typeof import('./components/chat/TypingIndicator.vue')['default']
  }
}
